version: '3'
services:
  testsamlidp_idp:
    build: .
    environment:
      VIRTUAL_HOST: idp.example.com
      MDX_URL: https://mdx.eduid.hu/entities
      SIMPLESAMLPHP_ADMIN_PASSWORD: test
      SIMPLESAMLPHP_SECRET_SALT: salt
    ports:
    - "80:80"
